[package]
name = "relm4_gtk_layer_shell_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
relm4 = "0.6.2"
relm4-components = "0.6.2"
gtk4-layer-shell = "0.0.3"
